### ISSUE TITLE
Error on /calendar page

### ISSUE THREAD

**Issue by pejuaxel** [pitaj/nodebb-plugin-calendar#71]
On the /calendar page, I'm getting this error: Cannot read property 'day' of undefined
Events do no show up.

I'm running NodeBB v1.5.0 and nodebb-plugin-calendar 1.0.0-alpha.27.
I'm getting this error whatever the user's language is.

Here is the error stack:

```
[Error] [object Object]
	(fonction anonyme) (calendar.js:1279)
	onack (nodebb.min.js:6:4435)
	onpacket (nodebb.min.js:6:3761)
	(fonction anonyme) (nodebb.min.js:6:5885)
	emit (nodebb.min.js:5:26704)
	ondecoded (nodebb.min.js:4:25698)
	(fonction anonyme) (nodebb.min.js:6:5885)
	emit (nodebb.min.js:4:19879)
	add (nodebb.min.js:4:5072)
	ondata (nodebb.min.js:4:25650)
	(fonction anonyme) (nodebb.min.js:6:5885)
	emit (nodebb.min.js:5:26704)
	onPacket (nodebb.min.js:5:2639)
	(fonction anonyme) (nodebb.min.js:5:202)
	emit (nodebb.min.js:5:26704)
	onPacket (nodebb.min.js:5:15163)
	onData (nodebb.min.js:5:15116)
	onmessage (nodebb.min.js:5:31636)
```

**Comment by pitaj** [comment]
Is this available on a public site for me to debug? I've been entirely unable to reproduce this. If not, please do the following: 

1. Produce the error
2. Open devtools
3. Click on the `calendar.js:1279` link in the error stacktrace
4. This will open the file source, if it's all jumbled up due to minification, please click on the `{}` button in the bottom left
5. This will prettify the output, which I'd like you to screenshot and post here

Thanks

**Comment by pejuaxel** [comment]
Yes, it's on : http://forum.assautsurlempire.fr/calendar
Cheers

**Comment by pitaj** [comment]
Great, thanks.

Ok, so I think I may have identified the problem, but I need your help still. Can you please edit `nodebb/node_modules/nodebb-plugin-calendar/build/lib/sockets.js` and change line 121 to this: 

    }, []).filter(Boolean);

If my theory is correct, that should fix the issue.

**Comment by pejuaxel** [comment]
I've edited the file and restarted nodebb but I still have the issue. Is there any other step to perform?

**Comment by pitaj** [comment]
Darn, I thought that would fix it.

Can you change line 85 from this:

      })(sock, data).asCallback(cb);

To this:
```js
  })(sock, data).asCallback((err, events) => cb(err && {
    message: err.message,
    stack: err.stack,
  }, events));
```

That should help me more easily debug this.

**Comment by pejuaxel** [comment]
I've edited the line. Can you debug it directly?

**Comment by archprateek** [comment]
@pejuaxel Have you been able to find a solution for this? Can you provide @pitaj required info so that he can look into this. I don't know how to produce stack trace. TIA.

**Comment by pejuaxel** [comment]
@archprateek Just had a second look at this. It seems that I haven't edited the correct line. Fixed now.

@pitaj I think you should be able to get the stack trace now on http://forum.assautsurlempire.fr/calendar

**Comment by pitaj** [comment]
Ok thanks I'll look at it

**Comment by pitaj** [comment]
Nope, unfortunately still unable to debug this. Can you try this instead?

Edit line 85 to be this: 

      })(sock, data).catch((err) => { throw Error(err.message); }).asCallback(cb);

**Comment by pejuaxel** [comment]
Line edited and NodeBB restarted :)
